version: "3.7"
services:
  destructive-farm:
    build: .
    restart: unless-stopped
    ports:
      - "5000:5001"
    volumes:
      - ./server/config.py:/app/server/config.py
      - ./server/db:/app/server/db

