version: "3.7"
services:
  destructive-farm:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: ./server/config.py
        target: /usr/src/app/server/config.py
      - type: bind
        source: ./server/flags.sqlite
        target: /usr/src/app/server/flags.sqlite
    restart: unless-stopped
