version: "3.7"
services:
  destructive-farm:
    build: .
    restart: unless-stopped
    ports:
      - "5001:5000"
    volumes:
      - ./server/config.py:/app/server/config.py
      - ./server/db:/usr/server/db

